Repository ASFHyP3/hyp3, pull requests merged in 2020-10, with the labels that each got.

#287 Release: v0.7.5
  .github/workflows/changelog.yml
  CHANGELOG.md
  apps/api/api-cf.yml
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/main-cf.yml
  apps/monitoring-cf.yml
  apps/workflow-cf.yml.j2
  job_types.yml
Labels: patch

#290 add permission to read users table
  apps/api/api-cf.yml
Labels: bumpless

#291 Update changelog with version number
  CHANGELOG.md
Labels: bumpless

#292 RELEASE: Add user specific quotas and job-id queries
  .gitignore
  CHANGELOG.md
  apps/api/api-cf.yml
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/util.py
  apps/main-cf.yml
  tests/api/cfg.env
  tests/api/conftest.py
  tests/api/test_get_job_by_id.py
  tests/api/test_get_user.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
Labels: minor

#293 added CoC and contributing guidelines
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
Labels: bumpless

#297 Release: v0.8.1
  .github/workflows/deploy.yml
  .github/workflows/deploy_autorift.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/main-cf.yml
Labels: patch

#298 RELEASE: DynamoDB paging
  CHANGELOG.md
  apps/api/src/hyp3_api/dynamo.py
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/util.py
  apps/start-execution/src/start_execution.py
  tests/api/test_dynamo.py
Labels: patch

#301 increase maximum cluster size
  CHANGELOG.md
  apps/compute-cf.yml
Labels: patch

#302 RELEASE: allow 200 concurrent instances
  CHANGELOG.md
  apps/compute-cf.yml
Labels: patch

#304 Release: root redirect to ui
  CHANGELOG.md
  apps/api/src/hyp3_api/handlers.py
  tests/api/test_api_spec.py
  tests/api/test_lambda_handler.py
Labels: patch

#306 reorder access log fields
  apps/api/api-cf.yml
Labels: bumpless
