Repository ASFHyP3/hyp3, pull requests merged in 2020-06, with the labels that each got.

#92 APD-1523: add s3 access logging for content bucket
  cloudformation.yml
Labels: enhancement

#90 pass job id as --bucket-prefix to rtc gamma container
  batch-cluster/cloudformation.yml
  step-function/cloudformation.yml
Labels: enhancement

#93 fix typo in step function definition
  step-function/cloudformation.yml
Labels: bug

#97 Production release
  batch-cluster/cloudformation.yml
  cloudformation.yml
  step-function/cloudformation.yml
Labels: enhancement

#103 Production deployment
  api/src/hyp3_api/openapi-spec.yml
  api/tests/test_hyp3_api.py
Labels: bug

#135 RELEASE: add expiration time and batch job limit
  api/src/hyp3_api/openapi-spec.yml
  api/tests/test_hyp3_api.py
  step-function/cloudformation.yml
  step-function/get-files/src/main.py
Labels: enhancement, minor

#136 use a common request time for all jobs in a batch
  api/src/hyp3_api/handlers.py
  api/tests/test_hyp3_api.py
Labels: minor

#139 add meaningful 403 forbidden error message
  api/src/hyp3_api/handlers.py
  api/tests/test_hyp3_api.py
Labels: enhancement, minor

#143 fix iam permissions for start-execution lambda
  step-function/start-execution/cloudformation.yml
Labels: bug

#144 Release: monthly job quota per user
  api/cloudformation.yml
  api/requirements.txt
  api/src/hyp3_api/handlers.py
  api/tests/cfg.env
  api/tests/test_hyp3_api.py
  cloudformation.yml
  step-function/start-execution/cloudformation.yml
  step-function/start-execution/src/main.py
Labels: enhancement
