Repository ASFHyP3/hyp3, pull requests merged in 2020-07, with the labels that each got.

#158 Add release workflow and granule checking
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  CHANGELOG.md
  api/requirements.txt
  api/src/hyp3_api/__init__.py
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/util.py
  api/tests/conftest.py
  api/tests/test_submit_job.py
Labels: enhancement, minor

#160 Add label and pr queries to release workflow
  .github/workflows/deploy.yml
Labels: CI/CD, minor

#162 Add checkout to release workflow
  .github/workflows/release.yml
Labels: minor

#173 Release v0.3.0: remove authz, lower quota, add documentation
  .github/workflows/deploy.yml
  CHANGELOG.md
  README.md
  api/cloudformation.yml
  api/src/hyp3_api/auth.py
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/openapi-spec.yml
  api/tests/cfg.env
  api/tests/conftest.py
  api/tests/test_api_spec.py
  api/tests/test_get_user.py
  api/tests/test_list_jobs.py
  api/tests/test_submit_job.py
  cloudformation.yml
Labels: documentation, enhancement, minor

#184 RELEASE: Check for DEM Coverage for submitted granules.
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  api/cloudformation.yml
  api/requirements-test.txt
  api/requirements.txt
  api/src/hyp3_api/__init__.py
  api/src/hyp3_api/dem_coverage_map.geojson
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/util.py
  api/src/hyp3_api/validation.py
  api/src/lambda_handler.py
  api/tests/conftest.py
  api/tests/test_api_spec.py
  api/tests/test_check_dem.py
  api/tests/test_get_user.py
  api/tests/test_submit_job.py
Labels: bug, enhancement, patch

#191 RELEASE: GRDH support, job retries, auto scale
  .github/workflows/deploy.yml
  CHANGELOG.md
  api/src/hyp3_api/openapi-spec.yml
  api/src/hyp3_api/validation.py
  api/tests/conftest.py
  api/tests/test_api_spec.py
  api/tests/test_submit_job.py
  batch-cluster/cloudformation.yml
  batch-cluster/launch-instance/cloudformation.yml
  batch-cluster/launch-instance/src/main.py
  batch-cluster/terminate-idle-instances/cloudformation.yml
  batch-cluster/terminate-idle-instances/src/main.py
  cloudformation.yml
  step-function/cloudformation.yml
Labels: enhancement, patch
