Repository ASFHyP3/hyp3, pull requests merged in 2020-12, with the labels that each got.

#317 fix s2 granule not found
  apps/api/src/hyp3_api/validation.py
  tests/api/test_validation.py
Labels: bumpless

#318 clarify api descriptions/examples for S2 granules
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
Labels: bumpless

#320 Release: v0.8.7
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/validation.py
  job_types.yml
  tests/api/test_validation.py
Labels: patch

#319 Add DOI to readme
  README.md
Labels: bumpless, documentation

#321 moved rtc job definition to use new gamma plugin
  .github/workflows/deploy.yml
  CHANGELOG.md
  job_types.yml
Labels: patch

#323 Release: update rtcGamma to use new generic Gamma plugin
  .github/workflows/deploy.yml
  CHANGELOG.md
  README.md
  job_types.yml
Labels: patch

#324 update insar gamma to use generic hyp3-gamma plugin
  CHANGELOG.md
  job_types.yml
Labels: patch

#325 Release InSAR GAMMA to use generic hyp3-gamma plugin
  CHANGELOG.md
  job_types.yml
Labels: patch

#327 Pull autorift container from west
  job_types.yml
Labels: bumpless
