Repository ASFHyP3/hyp3, pull requests merged in 2020-08, with the labels that each got.

#196 RELEASE: allow system to be easily shut down
  .github/workflows/tests.yml
  CHANGELOG.md
  api/cloudformation.yml
  api/requirements.txt
  api/src/hyp3_api/handlers.py
  api/tests/cfg.env
  api/tests/conftest.py
  api/tests/test_api_spec.py
  api/tests/test_get_user.py
  api/tests/test_submit_job.py
  batch-cluster/cloudformation.yml
  cloudformation.yml
Labels: patch

#201 RELEASE: job names
  CHANGELOG.md
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/openapi-spec.yml
  api/tests/conftest.py
  api/tests/test_list_jobs.py
  api/tests/test_submit_job.py
Labels: patch

#206 RELEASE: change browse image identification to use tags
  CHANGELOG.md
  api/src/hyp3_api/openapi-spec.yml
  batch-cluster/cloudformation.yml
  cloudformation.yml
  step-function/get-files/src/main.py
Labels: patch

#210 Add GetObjectTagging to get-files role
  CHANGELOG.md
  step-function/get-files/cloudformation.yml
Labels: bug

#211 RELEASE: fix get files IAM
  CHANGELOG.md
  step-function/get-files/cloudformation.yml
Labels: patch

#214 RELEASE: fix get_files key error
  CHANGELOG.md
  step-function/get-files/src/main.py
Labels: bug, patch

#221 RELEASE: bug fixes and unit tests
  .github/workflows/tests.yml
  CHANGELOG.md
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/openapi-spec.yml
  api/tests/conftest.py
  api/tests/test_submit_job.py
  requirements-test.txt
  step-function/cloudformation.yml
  step-function/get-files/test_get_files.py
Labels: CI/CD, bug, patch

#225 Release: remove description and revise DEM coverage checks
  CHANGELOG.md
  api/src/hyp3_api/openapi-spec.yml
  api/src/hyp3_api/validation.py
  api/tests/conftest.py
  api/tests/test_check_dem.py
  api/tests/test_submit_job.py
Labels: minor

#228 Release: new datatypes for api job parameters
  CHANGELOG.md
  api/src/hyp3_api/openapi-spec.yml
  step-function/start-execution/src/main.py
  step-function/start-execution/test_start_execution.py
Labels: minor

#231 Release v0.5.1
  CHANGELOG.md
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/util.py
  api/tests/conftest.py
Labels: bug, patch
