Repository ASFHyP3/hyp3, pull requests merged in 2020-09, with the labels that each got.

#251 Release: v0.6.1
  CHANGELOG.md
  api/cloudformation.yml
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/openapi-spec.yml
  api/tests/test_get_user.py
  batch-cluster/cloudformation.yml
  requirements-test.txt
Labels: patch

#258 Check for semantic version labels on PRs to master
  .github/workflows/labeled-pr.yml
Labels: CI/CD

#263 RELEASE: 0.7.0 autoRIFT
  .github/workflows/deploy.yml
  .github/workflows/deploy_autorift.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  README.md
  api/requirements.txt
  api/src/hyp3_api/api-spec/job_parameters.yml
  api/src/hyp3_api/api-spec/openapi-spec.yml
  api/src/hyp3_api/handlers.py
  api/src/hyp3_api/openapi.py
  api/src/hyp3_api/validation.py
  api/tests/test_check_dem.py
  api/tests/test_submit_job.py
  api/tests/test_validation.py
  batch-cluster/cloudformation.yml
  cloudformation.yml
  step-function/cloudformation.yml
  step-function/step-function.json
Labels: minor

#270 RELEASE: Hyp3 job type templating
  .github/workflows/deploy.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  apps/api/api-cf.yml
  apps/api/requirements-api.txt
  apps/api/src/hyp3_api/__init__.py
  apps/api/src/hyp3_api/__main__.py
  apps/api/src/hyp3_api/api-spec/job_parameters.yml
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/auth.py
  apps/api/src/hyp3_api/dem_coverage_map.geojson
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/lambda_handler.py
  apps/api/src/hyp3_api/openapi.py
  apps/api/src/hyp3_api/util.py
  apps/api/src/hyp3_api/validation.py
  apps/compute-cf.yml
  apps/get-files/get-files-cf.yml
  apps/get-files/src/get_files.py
  apps/main-cf.yml
  apps/render_cf.py
  apps/start-execution/src/start_execution.py
  apps/start-execution/start-execution-cf.yml
  apps/step-function.json.j2
  apps/update-db/src/main.py
  apps/update-db/update-db-cf.yml
  apps/workflow-cf.yml.j2
  batch-cluster/cloudformation.yml
  job_types.yml
  requirements-all.txt
  tests/api/cfg.env
  tests/api/conftest.py
  tests/api/test_api_spec.py
  tests/api/test_get_user.py
  tests/api/test_lambda_handler.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
  tests/api/test_validation.py
  tests/test_get_files.py
  tests/test_start_execution.py
Labels: patch

#273 update changelog for speckle filter fix
  CHANGELOG.md
Labels: bug, patch

#274 Release v0.7.2
  CHANGELOG.md
  job_types.yml
Labels: bug, patch

#276 Release: v0.7.3
  CHANGELOG.md
  apps/compute-cf.yml
Labels: patch

#278 Release: bumpless release to fix deploy_autorift workflow
  .github/workflows/deploy_autorift.yml
Labels: CI/CD, bug, bumpless

#281 Release v0.7.4
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/job_validation_map.yml.j2
  apps/api/src/hyp3_api/validation.py
  apps/render_cf.py
  apps/workflow-cf.yml.j2
  job_types.yml
Labels: patch

#283 Add a check for changelog changes
  .github/workflows/changelog.yml
Labels: CI/CD, bumpless

#284 drop retired ++entrypoint parameter from insar-gamma job definition
  job_types.yml
Labels: bumpless
