Repository ASFHyP3/hyp3, pull requests merged in 2021-07, with the labels that each got.

#464 update path to static files now that ui is hosted at ui/ instead of ui
  apps/api/src/hyp3_api/__init__.py
Labels: bumpless

#465 Release v2.0.1
  .github/pull_request_template.md
  .github/workflows/changelog.yml
  .github/workflows/deploy.yml
  .github/workflows/labeled-pr.yml
  CHANGELOG.md
  apps/api/requirements-api.txt
  apps/api/src/hyp3_api/__init__.py
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/routes.py
  tests/api/test_api_spec.py
  tests/api/test_submit_job.py
Labels: patch

#466 pin git-release version, add backmerge from main to develop
  .github/workflows/release.yml
Labels: bumpless

#468 add @ASFHyP3/platform to .github/CODEOWNERS
  .github/CODEOWNERS
Labels: bumpless

#471 populate possible job_types in OpenAPI spec dynamically
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
Labels: bumpless

#470 remove obsolete operationId values from openapi spec
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
Labels: bumpless

#469 convert tables fixture from a dictionary to a class
  tests/api/conftest.py
  tests/api/test_dynamo.py
  tests/api/test_get_job_by_id.py
  tests/api/test_get_user.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
Labels: bumpless

#472 add custom memory override for S2 autorift jobs
  apps/compute-cf.yml
  apps/step-function.json.j2
Labels: bumpless

#473 Revert "add custom memory override for S2 autorift jobs"
  apps/compute-cf.yml
  apps/step-function.json.j2
Labels: bumpless

#474 fix whitespace
  .github/CODEOWNERS
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: bumpless

#467 Release v2.0.2
  .github/CODEOWNERS
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  tests/api/conftest.py
  tests/api/test_dynamo.py
  tests/api/test_get_job_by_id.py
  tests/api/test_get_user.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
Labels: patch

#477 Try 4 per machine with s2
  apps/compute-cf.yml
  apps/step-function.json.j2
Labels: bumpless

#478 set S2 memory for 3 jobs/machine
  apps/step-function.json.j2
Labels: bumpless

#480 Try 5 per machine
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
Labels: bumpless

#486 Release v2.0.3
  CHANGELOG.md
  apps/step-function.json.j2
Labels: patch

#488 Fix back-merge
  .github/workflows/release.yml
Labels: CI/CD, bug, bumpless

#490 update description of include_inc_map api parameter
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
Labels: bumpless

#492 pin versions to make pip more performant during install
  apps/api/requirements-api.txt
  requirements-all.txt
Labels: bumpless

#493 support dependabot
  .github/dependabot.yml
Labels: bumpless
