Repository ASFHyP3/hyp3, pull requests merged in 2021-01, with the labels that each got.

#329 add s3 info to files block for jobs
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/get-files/src/get_files.py
  tests/api/test_list_jobs.py
  tests/test_get_files.py
Labels: minor

#330 update readme, resolve bugs submitting autorift jobs for S2/LC08 gran…
  README.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/validation.py
  tests/api/test_submit_job.py
  tests/api/test_validation.py
Labels: bumpless

#331 Release Landsat support for autoRIFT
  CHANGELOG.md
  README.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/auth.py
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/validation.py
  job_types.yml
  tests/api/test_submit_job.py
  tests/api/test_validation.py
Labels: patch

#339 RELEASE: 0.8.11
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/get-files/src/get_files.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
  tests/test_get_files.py
Labels: patch
