Repository ASFHyP3/hyp3, pull requests merged in 2021-05, with the labels that each got.

#411 don't validate landsat-8 scenes against CMR, regardless of sensor mode
  apps/api/src/hyp3_api/validation.py
  tests/api/test_validation.py
Labels: bumpless

#416 use http.HTTPStatus instead of flask_api.status in API testing
  apps/api/requirements-api.txt
  tests/api/test_api_spec.py
  tests/api/test_get_job_by_id.py
  tests/api/test_get_user.py
  tests/api/test_lambda_handler.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
Labels: bumpless

#418 Release include_dem parameter for InSAR jobs
  CHANGELOG.md
  apps/api/requirements-api.txt
  job_types.yml
  tests/api/test_api_spec.py
  tests/api/test_get_job_by_id.py
  tests/api/test_get_user.py
  tests/api/test_lambda_handler.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
Labels: patch

#420 Update README instructions for running tests and running the API locally
  README.md
Labels: bumpless

#422 Release include_wrapped_phase option for InSAR jobs
  CHANGELOG.md
  README.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  job_types.yml
  tests/api/test_submit_job.py
Labels: patch

#423 fix merge conflict in README
  README.md
Labels: bumpless

#425 Use a GitHub action and matrix to deploy HyP3
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  .github/workflows/deploy_autorift.yml
Labels: CI/CD, bumpless

#427 Fix matrix deploy refs
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#428 Use env secrets for AWS access
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#429 Add WATER_MAP as option for job_type API parameter
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
Labels: bumpless

#430 fix indentation for water map parameters
  job_types.yml
Labels: bumpless
