Repository ASFHyP3/hyp3, pull requests merged in 2021-11, with the labels that each got.

#655 indentation cleanup in job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
Labels: bumpless

#656 refactor job_parameters.yml.j2 to correctly parse required parameters
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  tests/test_api/test_submit_job.py
  tests/test_api/test_subscriptions.py
Labels: bumpless

#657 flag job_type and name as required for subscription job specifications
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
Labels: bumpless

#658 flag job_type and job_parameters as required for POST /jobs schema
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
Labels: bumpless

#660 flag additional fields as required in GET /subscriptions responses
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  tests/test_dynamo/test_util.py
Labels: bumpless

#659 RELEASE: 2.6.4
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/process-new-granules/src/process_new_granules.py
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  lib/dynamo/dynamo/util.py
  tests/test_api/test_submit_job.py
  tests/test_api/test_subscriptions.py
  tests/test_dynamo/test_util.py
Labels: bug, patch

#652 Sync hyp3-isce with HyP3 v2.6.4
  .github/actions/deploy-hyp3/action.yml
  .github/dependabot.yml
  .github/workflows/deploy.yml
  CHANGELOG.md
  Makefile
  README.md
  apps/api/api-cf.yml
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/job_validation_map.yml.j2
  apps/compute-cf.yml
  apps/get-files/get-files-cf.yml
  apps/main-cf.yml
  apps/process-new-granules/process-new-granules-cf.yml
  apps/process-new-granules/src/process_new_granules.py
  apps/render_cf.py
  apps/start-execution/start-execution-cf.yml
  apps/step-function.json.j2
  apps/update-db/update-db-cf.yml
  apps/upload-log/upload-log-cf.yml
  apps/workflow-cf.yml.j2
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE.yml
  job_spec/RTC_GAMMA.yml
  job_types.yml
  lib/dynamo/dynamo/util.py
  tests/test_api/test_submit_job.py
  tests/test_api/test_subscriptions.py
  tests/test_dynamo/test_util.py
Labels: CI/CD, bumpless

#663 echo templates in make render; render all templates during static ana…
  .github/actions/deploy-hyp3/action.yml
  .github/dependabot.yml
  .github/workflows/static-analysis.yml
  Makefile
  README.md
  apps/process-new-granules/requirements-process-new-granules.txt
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-process-new-granules.txt
  requirements-apps-start-execution.txt
  requirements-apps-update-db.txt
Labels: bumpless

#666 update example secondary granule for isce jobs
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
Labels: bumpless

#689 Release 2.6.5
  .github/actions/deploy-hyp3/action.yml
  .github/dependabot.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  Makefile
  README.md
  apps/api/requirements-api.txt
  apps/process-new-granules/requirements-process-new-granules.txt
  apps/start-execution/start-execution-requirements.txt
  apps/update-db/update-db-requirements.txt
  apps/workflow-cf.yml.j2
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/RTC_GAMMA.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-process-new-granules.txt
  requirements-apps-start-execution.txt
  requirements-apps-update-db.txt
Labels: patch

#697 Release v2.6.6
  CHANGELOG.md
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/routes.py
  requirements-all.txt
  requirements-apps-api.txt
  tests/test_api/test_api_spec.py
Labels: patch

#699 refactor scale_cluster.py
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  apps/compute-cf.yml
  apps/main-cf.yml
  apps/scale-cluster/src/scale_cluster.py
  tests/test_scale_cluster.py
Labels: bumpless

#700 add test_set_max_vcpus
  CHANGELOG.md
  tests/test_scale_cluster.py
Labels: bumpless

#701 Release v2.7.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  CHANGELOG.md
  Makefile
  README.md
  apps/compute-cf.yml
  apps/main-cf.yml
  apps/scale-cluster/scale-cluster-cf.yml
  apps/scale-cluster/src/scale_cluster.py
  requirements-all.txt
  requirements-apps-scale-cluster.txt
  tests/test_scale_cluster.py
Labels: minor
