Repository ASFHyP3/hyp3, pull requests merged in 2021-10, with the labels that each got.

#592 Add parameter file option for autorift
  apps/main-cf.yml
  apps/workflow-cf.yml.j2
  job_types.yml
Labels: bumpless

#593 add cicd for autorift in eu
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#594 deploy autorift into eu
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  apps/main-cf.yml
  apps/workflow-cf.yml.j2
  job_types.yml
Labels: bumpless

#595 Cloudformation requires template buckets be in same region as stack d…
  .github/workflows/deploy.yml
Labels: bumpless

#596 Deploy autorift with in region template bucket
  .github/workflows/deploy.yml
Labels: bumpless

#597 Add autorift image as a parameter
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  apps/main-cf.yml
  apps/workflow-cf.yml.j2
  job_types.yml
Labels: bumpless

#599 Add autorift eu parameter file location
  .github/workflows/deploy.yml
Labels: bumpless

#598 release autorift image parameter
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  apps/main-cf.yml
  apps/workflow-cf.yml.j2
  job_types.yml
Labels: bumpless

#600 add insar isce plugin
  .github/workflows/deploy.yml
  Makefile
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  job_types.yml
Labels: bumpless

#602 Use hyp3-isce environment
  .github/workflows/deploy.yml
Labels: bumpless

#605 update isce to use image tag latest
  .github/workflows/deploy.yml
Labels: bumpless

#616 Jpl docker
  .github/workflows/deploy.yml
  job_types.yml
Labels: bumpless

#620 RELEASE: 2.6.0
  .github/actions/deploy-hyp3/action.yml
  CHANGELOG.md
  Makefile
  README.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/job_validation_map.yml.j2
  apps/render_cf.py
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
  job_spec/AUTORIFT.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/RTC_GAMMA.yml
  job_types.yml
Labels: minor

#623 change name of compute environment resource to force replacement
  apps/compute-cf.yml
Labels: bumpless

#624 Revert "change name of compute environment resource to force replacement"
  apps/compute-cf.yml
Labels: bumpless

#626 change name of compute environment resource to force replacement (again)
  apps/compute-cf.yml
Labels: bumpless

#638 Don't fail all deployments if one fails
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#640 fix AmiId parameter type in compute-cf.yml
  apps/compute-cf.yml
Labels: bumpless
