Repository ASFHyP3/hyp3, pull requests merged in 2021-08, with the labels that each got.

#504 Release v2.0.4
  .github/actions/deploy-hyp3/action.yml
  .github/dependabot.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  CHANGELOG.md
  apps/api/requirements-api.txt
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/main-cf.yml
  apps/workflow-cf.yml.j2
  job_types.yml
  requirements-all.txt
Labels: patch

#513 fix environment variable name for update-db lambda function
  apps/update-db/update-db-cf.yml
Labels: bumpless

#514 migrate start_execution.get_pending_jobs to dynamo.jobs.get_jobs_by_s…
  .github/actions/deploy-hyp3/action.yml
  README.md
  apps/start-execution/src/start_execution.py
  apps/start-execution/start-execution-cf.yml
  apps/start-execution/start-execution-requirements.txt
  lib/dynamo/dynamo/jobs.py
  requirements-all.txt
  tests/test_dynamo.py
  tests/test_start_execution.py
Labels: bumpless

#515 refactor dynamo.jobs.put_jobs to not mutate input dictionary
  lib/dynamo/dynamo/jobs.py
  tests/test_dynamo.py
Labels: bumpless

#516 disable deploying to autorift environment while landsat 8 campaign is…
  .github/workflows/deploy.yml
Labels: bumpless

#517 Release v2.1.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  apps/api/requirements-api.txt
  apps/api/src/hyp3_api/__init__.py
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/util.py
  apps/start-execution/src/start_execution.py
  apps/start-execution/start-execution-cf.yml
  apps/start-execution/start-execution-requirements.txt
  apps/update-db/src/main.py
  apps/update-db/update-db-cf.yml
  apps/update-db/update-db-requirements.txt
  lib/dynamo/dynamo/__init__.py
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/user.py
  lib/dynamo/dynamo/util.py
  lib/dynamo/setup.py
  requirements-all.txt
  tests/api/conftest.py
  tests/api/test_get_user.py
  tests/api/test_list_jobs.py
  tests/api/test_submit_job.py
  tests/cfg.env
  tests/conftest.py
  tests/test_dynamo.py
  tests/test_start_execution.py
Labels: minor

#518 move retry strategy for containers to Batch from Step Functions
  apps/step-function.json.j2
Labels: bumpless

#519 revise cloudwatch logs retry strategy
  .github/workflows/deploy.yml
  CHANGELOG.md
  apps/upload-log/src/upload_log.py
Labels: minor

#520 Release v2.1.1
  .github/workflows/deploy.yml
  CHANGELOG.md
  apps/step-function.json.j2
  apps/upload-log/src/upload_log.py
Labels: patch

#521 Refactor subscription search parameters
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/process-new-granules/src/process_new_granules.py
  lib/dynamo/dynamo/subscriptions.py
  tests/api/test_subscriptions.py
  tests/test_dynamo.py
Labels: bumpless

#524 implement dynamo.util tests
  lib/dynamo/dynamo/util.py
  tests/test_dynamo/test_jobs.py
  tests/test_dynamo/test_subscriptions.py
  tests/test_dynamo/test_util.py
Labels: bumpless

#525 revert subscription changes to deploy matrix
  .github/workflows/deploy.yml
Labels: bumpless

#526 add dictionary wrapper with subscriptions key to GET /subscriptions r…
  apps/api/src/hyp3_api/handlers.py
  tests/test_api/test_subscriptions.py
Labels: bumpless

#532 validate end dates in patch subscriptions
  apps/api/src/hyp3_api/handlers.py
  tests/test_api/test_subscriptions.py
Labels: bug, bumpless

#533 allow GetItem on subscriptions table for API lambda
  apps/api/api-cf.yml
Labels: bumpless

#534 fix syntax error in process_new_granules.py
  apps/process-new-granules/src/process_new_granules.py
Labels: bumpless

#536 fix syntax error in process_new_granules
  apps/process-new-granules/src/process_new_granules.py
Labels: bumpless

#537 add api test test_update_subscription_not_found
  tests/test_api/test_subscriptions.py
Labels: bumpless

#539 fix process_new_granules bug
  apps/process-new-granules/src/process_new_granules.py
Labels: bumpless

#541 increase process_new_granules timeout to 900 seconds
  apps/process-new-granules/process-new-granules-cf.yml
Labels: bumpless

#543 skip put_jobs call when there are no new jobs to submit
  apps/process-new-granules/src/process_new_granules.py
Labels: bumpless

#544 Expand test_process_new_granules
  .github/workflows/static-analysis.yml
  apps/process-new-granules/src/process_new_granules.py
  tests/test_process_new_granules.py
Labels: bumpless

#545 add test_get_unprocessed_granules
  tests/test_process_new_granules.py
Labels: bumpless
