Repository ASFHyP3/hyp3, pull requests merged in 2021-04, with the labels that each got.

#387 update description of dem_name parameter
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
Labels: bumpless

#390 Release dem_name parameter for RTC and improved quota check performance
  CHANGELOG.md
  README.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/dem_coverage_map_cop30.geojson
  apps/api/src/hyp3_api/dem_coverage_map_legacy.geojson
  apps/api/src/hyp3_api/dynamo.py
  apps/api/src/hyp3_api/util.py
  apps/api/src/hyp3_api/validation.py
  job_types.yml
  tests/api/test_dynamo.py
  tests/api/test_validation.py
Labels: minor

#395 Hotfix names
  CHANGELOG.md
  apps/api/src/hyp3_api/handlers.py
Labels: patch

#397 redo copernicus for insar changes reverted by backmerge of main into …
  apps/api/src/hyp3_api/validation.py
  tests/api/test_validation.py
Labels: bumpless

#398 Release Copernicus DEM for InSAR
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/dynamo.py
  apps/api/src/hyp3_api/validation.py
  tests/api/test_validation.py
Labels: patch

#401 add pull request templates
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
Labels: bumpless

#402 update to api gateway payload v2.0
  apps/api/api-cf.yml
Labels: bumpless

#403 Release include_inc_map option for InSAR
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  CHANGELOG.md
  apps/api/api-cf.yml
  job_types.yml
  tests/api/test_lambda_handler.py
Labels: patch

#406 move apply_water_mask from rtc to insar
  job_types.yml
Labels: bumpless

#407 include tests for expected insar parameters
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  job_types.yml
  tests/api/test_submit_job.py
Labels: bumpless
