Repository ASFHyP3/hyp3, pull requests merged in 2021-09, with the labels that each got.

#551 fix response types for subscriptions
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
Labels: bumpless

#552 add option to enable/disable subscriptions
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/process-new-granules/src/process_new_granules.py
  lib/dynamo/dynamo/subscriptions.py
  tests/test_api/test_subscriptions.py
  tests/test_dynamo/test_subscriptions.py
  tests/test_process_new_granules.py
Labels: bumpless

#555 change api-spec to be more clear
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
Labels: bumpless

#554 RELEASE: Subscriptions
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  apps/api/api-cf.yml
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/routes.py
  apps/main-cf.yml
  apps/process-new-granules/process-new-granules-cf.yml
  apps/process-new-granules/requirements-process-new-granules.txt
  apps/process-new-granules/src/process_new_granules.py
  apps/render_cf.py
  job_types.yml
  lib/dynamo/dynamo/__init__.py
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/subscriptions.py
  lib/dynamo/dynamo/user.py
  lib/dynamo/dynamo/util.py
  requirements-all.txt
  tests/cfg.env
  tests/conftest.py
  tests/test_api/__init__.py
  tests/test_api/conftest.py
  tests/test_api/test_api_spec.py
  tests/test_api/test_get_job_by_id.py
  tests/test_api/test_get_user.py
  tests/test_api/test_lambda_handler.py
  tests/test_api/test_list_jobs.py
  tests/test_api/test_submit_job.py
  tests/test_api/test_subscriptions.py
  tests/test_api/test_util.py
  tests/test_api/test_validation.py
  tests/test_dynamo/__init__.py
  tests/test_dynamo/test_jobs.py
  tests/test_dynamo/test_subscriptions.py
  tests/test_dynamo/test_user.py
  tests/test_dynamo/test_util.py
  tests/test_process_new_granules.py
Labels: minor

#556 make sure cfn-lint runs during static analysis
  .github/workflows/static-analysis.yml
Labels: bumpless

#560 grant process_new_granules dynamodb:PutItem on the subscriptions table
  apps/process-new-granules/process-new-granules-cf.yml
Labels: bumpless

#561 don't mutate input subscription in process_new_granules.get_jobs_for_…
  apps/process-new-granules/src/process_new_granules.py
  tests/test_process_new_granules.py
Labels: bumpless

#562 RELEASE: 2.3.1
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/routes.py
  apps/process-new-granules/process-new-granules-cf.yml
  apps/process-new-granules/src/process_new_granules.py
  lib/dynamo/dynamo/jobs.py
  tests/test_api/conftest.py
  tests/test_api/test_list_jobs.py
  tests/test_dynamo/test_jobs.py
  tests/test_process_new_granules.py
Labels: minor

#566 RELEASE: 2.4.1
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  tests/test_api/test_subscriptions.py
Labels: patch

#571 add new index without removing old index
  apps/main-cf.yml
Labels: bumpless

#569 RELEASE 2.4.2
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/routes.py
  apps/main-cf.yml
  lib/dynamo/dynamo/subscriptions.py
  tests/test_api/test_subscriptions.py
  tests/test_dynamo/test_subscriptions.py
  tests/test_process_new_granules.py
Labels: patch

#572 remove index user-id
  apps/main-cf.yml
Labels: bumpless

#573 remove user_id index from subscriptions table
  apps/main-cf.yml
Labels: bumpless

#574 add index user_id with range key on creation_date
  apps/main-cf.yml
Labels: bumpless

#575 Add key user_id with range key
  apps/main-cf.yml
Labels: bumpless

#576 remove temporary index user_id_by_creation_date
  apps/main-cf.yml
  lib/dynamo/dynamo/subscriptions.py
Labels: bumpless

#577 remove temportary index user_id_by_creation_date
  apps/main-cf.yml
  lib/dynamo/dynamo/subscriptions.py
Labels: bumpless

#582 Use ResourceRequirements to override container memory
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
Labels: bumpless

#586 must specify VCPU in job definition ResourceRequirements in addition …
  apps/workflow-cf.yml.j2
Labels: bumpless

#585 Makefile
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  Makefile
  README.md
Labels: bumpless

#591 Release quota and displacement maps (attempt #2)
  .github/workflows/deploy.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  Makefile
  README.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
  job_types.yml
  tests/test_api/test_submit_job.py
  tests/test_api/test_subscriptions.py
Labels: minor
