Repository ASFHyP3/hyp3, pull requests merged in 2021-12, with the labels that each got.

#710 remove duplicate implementation of get_max_jobs_per_month
  apps/api/src/hyp3_api/handlers.py
Labels: bumpless

#713 Release v2.7.1
  CHANGELOG.md
  apps/api/api-cf.yml
  apps/api/src/hyp3_api/handlers.py
  apps/main-cf.yml
  requirements-all.txt
Labels: patch

#714 Switch autoRIFT job to Github Container Registry
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
Labels: bumpless

#720 Bumpless Release
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  requirements-all.txt
Labels: bumpless

#718 Add water map job to HyP3 test
  .github/workflows/deploy.yml
  job_spec/WATER_MAP.yml
Labels: CI/CD, bumpless

#719 Bring ISCE deployments into normal deployment workflow
  .github/workflows/deploy.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
Labels: CI/CD, bumpless

#723 Chomp newline in YAML
  .github/workflows/deploy.yml
Labels: bug, CI/CD, bumpless

#724 Bumpless Release
  .github/workflows/deploy.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
  job_spec/WATER_MAP.yml
Labels: bumpless

#728 fix scale-cluster iam policy
  apps/scale-cluster/scale-cluster-cf.yml
Labels: bumpless

#721 add cicd deployment code for edc-uat
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#730 add session token
  .github/workflows/deploy.yml
Labels: bumpless

#731 use iam permissions boundary and vpc in edc
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
Labels: bumpless

#732 allow secret to default to empty string
  .github/workflows/deploy.yml
Labels: bumpless

#733 bring up to date with develop and deploy lambdas in vpc
  .github/workflows/deploy.yml
Labels: bumpless

#734 fix name of input parameter
  .github/actions/deploy-hyp3/action.yml
Labels: bumpless

#736 skeleton of converting DeployLambasInVpc stack param to EarthdataClou…
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  apps/main-cf.yml
Labels: CI/CD, bumpless

#740 add contition to cf deployment role statement to allow deploying with…
  .github/actions/deploy-hyp3/action.yml
Labels: bumpless

#741 update stackname to include 'hyp3'
  .github/workflows/deploy.yml
Labels: bumpless

#742 add session token to deployment authentication
  .github/workflows/deploy.yml
Labels: bumpless

#743 RELEASE: 2.7.2
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  CHANGELOG.md
  apps/main-cf.yml
  apps/scale-cluster/scale-cluster-cf.yml
  apps/scale-cluster/src/scale_cluster.py
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-process-new-granules.txt
  tests/test_scale_cluster.py
Labels: patch

#746 Add encryption to log bucket
  CHANGELOG.md
  apps/main-cf.yml
Labels: patch

#749 update make cfn-lint to recurse through directories correctly
  Makefile
Labels: bumpless

#751 Release v2.7.3
  CHANGELOG.md
  Makefile
  apps/main-cf.yml
  requirements-apps-api.txt
Labels: patch

#748 deploy to Earthdata Cloud using EDC-specific Ami
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
Labels: bumpless

#752 reduce fleet size in hyp3-edc-uat environment pending access to large…
  .github/workflows/deploy.yml
Labels: bumpless

#761 Release v2.7.4
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  CHANGELOG.md
  apps/main-cf.yml
  apps/monitoring-cf.yml
  requirements-all.txt
Labels: patch
