Repository ASFHyP3/hyp3, pull requests merged in 2021-06, with the labels that each got.

#431 single quotes for cloudformation parameter values
  .github/actions/deploy-hyp3/action.yml
Labels: bumpless

#432 correct water map parameter name in job_types.yml
  job_types.yml
Labels: bumpless

#433 Merge develop into watermap
  .github/actions/deploy-hyp3/action.yml
Labels: bumpless

#434 increase timeout for WATER_MAP jobs to 180 minutes
  job_types.yml
Labels: bumpless

#435 increase water map timeout to six hours
  job_types.yml
Labels: bumpless

#436 Fix prod env name
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#438 use default memory from job definition for S1 scenes
  apps/step-function.json.j2
Labels: bumpless

#439 use default memory from job definition for S1 scenes
  apps/step-function.json.j2
Labels: bumpless

#440 Release memory optimization and matrix builds
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  .github/workflows/deploy_autorift.yml
  CHANGELOG.md
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
Labels: patch

#441 Add python setup and dependencies to tag job
  .github/workflows/deploy.yml
Labels: CI/CD, bug, bumpless

#442 Watermap default threshold values
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
Labels: bug, bumpless

#445 modify ec2 instance type, add 10.0 as resolution option for RTC_GAMMA…
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/compute-cf.yml
  job_types.yml
Labels: bumpless

#446 increase default memory reservation to 63 GB to support 10m jobs
  apps/workflow-cf.yml.j2
Labels: bumpless

#447 Decimal inexact fix
  CHANGELOG.md
  apps/api/src/hyp3_api/util.py
  tests/api/test_dynamo.py
Labels: bug, patch

#449 increase watermap timeout to 24 hours
  job_types.yml
Labels: bumpless

#450 More memory for 10m RTC
  apps/compute-cf.yml
  apps/workflow-cf.yml.j2
Labels: bumpless

#453 Release decimal and start_execution bug fixes
  .github/workflows/deploy.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/util.py
  apps/start-execution/src/start_execution.py
  tests/api/conftest.py
  tests/api/test_dynamo.py
  tests/conftest.py
  tests/test_start_execution.py
Labels: patch

#454 Update water map default vv/vh thresholds
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/start-execution/src/start_execution.py
  job_types.yml
  tests/api/conftest.py
  tests/conftest.py
  tests/test_start_execution.py
Labels: bumpless

#458 Update CHANGELOG.md
  CHANGELOG.md
Labels: bumpless

#457 Release 2.0.0
  CHANGELOG.md
  apps/api/requirements-api.txt
  apps/api/src/hyp3_api/__init__.py
  apps/api/src/hyp3_api/__main__.py
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/auth.py
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/lambda_handler.py
  apps/api/src/hyp3_api/openapi.py
  apps/api/src/hyp3_api/routes.py
  apps/api/src/hyp3_api/ui/README.md
  apps/api/src/hyp3_api/ui/SWAGGER_LICENSE
  apps/api/src/hyp3_api/ui/swagger/favicon-16x16.png
  apps/api/src/hyp3_api/ui/swagger/favicon-32x32.png
  apps/api/src/hyp3_api/ui/swagger/index.html
  apps/api/src/hyp3_api/ui/swagger/oauth2-redirect.html
  apps/api/src/hyp3_api/ui/swagger/swagger-ui-bundle.js
  apps/api/src/hyp3_api/ui/swagger/swagger-ui-es-bundle-core.js
  apps/api/src/hyp3_api/ui/swagger/swagger-ui-es-bundle.js
  apps/api/src/hyp3_api/ui/swagger/swagger-ui-standalone-preset.js
  apps/api/src/hyp3_api/ui/swagger/swagger-ui.css
  apps/api/src/hyp3_api/ui/swagger/swagger-ui.js
  tests/api/conftest.py
Labels: major

#459 master -> main
  .github/pull_request_template.md
  .github/workflows/changelog.yml
  .github/workflows/deploy.yml
  .github/workflows/labeled-pr.yml
Labels: CI/CD, bumpless

#461 upgrade to serverless_wsgi 1.7.8 to remove need to pin Werkzeug version
  apps/api/requirements-api.txt
Labels: bumpless
