Repository ASFHyP3/hyp3, pull requests merged in 2021-03, with the labels that each got.

#372 Release bucket permission changes
  CHANGELOG.md
  apps/main-cf.yml
Labels: patch

#370 Have get-files ignore side-loaded product files (should be temporary!)
  apps/get-files/src/get_files.py
  tests/test_get_files.py
Labels: bumpless

#374 Release get-files changes to ignore unzipped product files
  CHANGELOG.md
  apps/get-files/src/get_files.py
  tests/test_get_files.py
Labels: patch

#377 increase INSAR_GAMMA timeout to 3 hours
  job_types.yml
Labels: bumpless

#381 RELEASE 1.0.0
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/dynamo.py
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/util.py
  job_types.yml
  tests/api/conftest.py
  tests/api/test_dynamo.py
  tests/api/test_list_jobs.py
  tests/api/test_util.py
Labels: major

#385 Update deployment instructions in README.md
  README.md
Labels: bumpless
