Repository ASFHyP3/hyp3, pull requests merged in 2022-06, with the labels that each got.

#1043 Specified new version for DEM release
  CHANGELOG.md
Labels: bumpless

#1042 Update-DEM
  CHANGELOG.md
  apps/api/src/hyp3_api/dem_coverage_map_cop30.geojson
  requirements-all.txt
  requirements-apps-process-new-granules.txt
  tests/test_api/test_validation.py
Labels: patch

#1047 reduce maximum vcpus in hyp3-isce environment
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1048 Release 2.18.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/api/api-cf.yml.j2
  apps/api/src/hyp3_api/routes.py
  apps/main-cf.yml.j2
  requirements-all.txt
  tests/test_api/test_api_spec.py
  tests/test_api/test_lambda_handler.py
Labels: minor

#1053 Release v2.18.1
  CHANGELOG.md
  apps/process-new-granules/process-new-granules-cf.yml.j2
  requirements-all.txt
Labels: patch

#1057 remove hyp3-test from daac deployment matrix
  .github/workflows/deploy-daac.yml
Labels: bumpless

#1058 reduce max_vcpus for hyp3-tibet deployment
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1059 Add missing job types to EDC-UAT.
  .github/workflows/deploy-daac.yml
Labels: bumpless

#1060 Bumpless release
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  requirements-all.txt
  requirements-apps-api.txt
Labels: bumpless

#1063 drop hyp3 evironment from deploy-daac.yml
  .github/workflows/deploy-daac.yml
Labels: bumpless

#1065 Allow updating subscription start datetime and AOI
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  tests/test_api/test_subscriptions.py
Labels: minor

#1067 Release 2.19.0
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  apps/process-new-granules/src/process_new_granules.py
  requirements-all.txt
  tests/test_api/test_subscriptions.py
Labels: minor

#1068 remove hyp3-isce environment from deploy-enterprise.yml
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1069 add debug logging to GET /jobs
  apps/api/src/hyp3_api/handlers.py
Labels: bumpless

#1073 remove root path when building next url
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/util.py
  tests/test_api/test_util.py
Labels: bumpless

#1075 tweak changelog
  CHANGELOG.md
Labels: bumpless

#1074 Release v2.19.1
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/util.py
  requirements-all.txt
  tests/test_api/test_list_jobs.py
  tests/test_api/test_util.py
Labels: patch

#1083 remove hyp3-tibet from deploy-enterprise.yml
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1077 Include deployment name in API page header
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  .gitignore
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/ui/swagger/index.html.j2
  apps/render_cf.py
Labels: patch

#1088 Release 2.19.2
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  .gitignore
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/ui/swagger/index.html.j2
  apps/render_cf.py
  requirements-all.txt
  requirements-apps-api.txt
Labels: patch

#1094 Revert "Bump asf-search from 3.2.2 to 4.0.0"
  requirements-apps-process-new-granules.txt
Labels: bumpless

#1085 Add action for Hyp3 Deployment for NISAR GUNW products
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1093 Add enterprise test deployment
  .github/workflows/deploy-enterprise-test.yml
Labels: bumpless

#1097 Temporarily pin AVO hyp3-gamma image tag
  .github/workflows/deploy-enterprise.yml
Labels: bumpless
