Repository ASFHyP3/hyp3, pull requests merged in 2022-10, with the labels that each got.

#1231 Improve subscription manager/worker logging
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
  tests/test_subscription_manager.py
Labels: bumpless

#1232 add c5d.xlarge back to GUNW deployments
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1234 Release 2.21.2
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  Makefile
  apps/main-cf.yml.j2
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-manager/subscription-manager-cf.yml.j2
  apps/subscription-worker/src/subscription_worker.py
  apps/subscription-worker/subscription-worker-cf.yml.j2
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-process-new-granules.txt
  requirements-apps-subscription-manager.txt
  requirements-apps-subscription-worker.txt
  tests/test_subscription_manager.py
  tests/test_subscription_worker.py
Labels: patch

#1238 automate updates of github action versions
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
Labels: bumpless

#1247 add temporary hyp3-edc-contingency environment to deploy-daac.yml
  .github/workflows/deploy-daac.yml
Labels: bumpless

#1250 Release L457 and add deployment for AZ DWR
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  requirements-all.txt
  tests/test_api/test_submit_job.py
Labels: patch

#1253 Log AWS request ID in subscription lambdas
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
  tests/test_subscription_manager.py
  tests/test_subscription_worker.py
Labels: bug, bumpless

#1254 Revert "Log AWS request ID in subscription lambdas"
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
  tests/test_subscription_manager.py
  tests/test_subscription_worker.py
Labels: bumpless

#1256 Implement subscription lambda logging the right way
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
Labels: bug, bumpless

#1255 Revert "add temporary hyp3-edc-contingency environment to deploy-daac.yml"
  .github/workflows/deploy-daac.yml
Labels: bumpless

#1264 drop unused LambdaArn output from subscription manager cloudformation template
  apps/subscription-manager/subscription-manager-cf.yml.j2
Labels: bumpless

#1277 Release v2.21.5
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1289 Log unhandled exceptions in lambdas with logging configured
  apps/start-execution-manager/src/start_execution_manager.py
  apps/start-execution-worker/src/start_execution_worker.py
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
Labels: bumpless

#1297 Release v2.21.7
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1299 Revert "Log unhandled exceptions in lambdas with logging configured"
  apps/start-execution-manager/src/start_execution_manager.py
  apps/start-execution-worker/src/start_execution_worker.py
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
Labels: bumpless
