Repository ASFHyP3/hyp3, pull requests merged in 2022-09, with the labels that each got.

#1175 Release 2.20.0
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/get-files/src/get_files.py
  apps/render_cf.py
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
  job_spec/RIVER_WIDTH.yml
  job_spec/RTC_GAMMA.yml
  job_spec/RTC_GAMMA_10M.yml
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_10M.yml
  requirements-all.txt
  requirements-apps-api.txt
Labels: minor

#1183 Pin cryptography version to <38
  requirements-apps-api.txt
Labels: bumpless

#1184 Specify pip platform and upgrade cryptography
  Makefile
  requirements-apps-api.txt
Labels: bug, bumpless

#1185 Revert "Specify pip platform and upgrade cryptography"
  Makefile
  requirements-apps-api.txt
Labels: bumpless

#1191 pin cryptography to 37.0.4 and ignore future dependabot updates
  .github/dependabot.yml
  requirements-apps-api.txt
Labels: bumpless

#1172 Compute processing time for each Batch job
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/check-processing-time/src/check_processing_time.py
  apps/step-function.json.j2
  apps/upload-log/src/upload_log.py
  tests/test_check_processing_time.py
  tests/test_upload_log.py
Labels: minor

#1194 ignore openapi-spec-validator in dependabot.yml
  .github/dependabot.yml
Labels: bumpless

#1195 use openapi-spec-validator during make openapi-validate
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  requirements-all.txt
Labels: bumpless

#1189 upgrade moto to v4.0.2
  .github/dependabot.yml
  requirements-all.txt
  tests/conftest.py
Labels: bumpless

#1199 Release 2.21.0
  .github/dependabot.yml
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/check-processing-time/src/check_processing_time.py
  apps/step-function.json.j2
  apps/upload-log/src/upload_log.py
  requirements-all.txt
  tests/conftest.py
  tests/test_check_processing_time.py
  tests/test_upload_log.py
Labels: minor

#1205 Update release template
  .github/PULL_REQUEST_TEMPLATE/release.md
Labels: bumpless

#1206 Add PR template comment action
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/workflows/release-template-comment.yml
Labels: CI/CD, bumpless

#1208 drop description from release template comment
  .github/workflows/release-template-comment.yml
Labels: CI/CD, bumpless

#1209 Only comment on a release PR when it's opened
  .github/workflows/release-template-comment.yml
Labels: CI/CD, bumpless

#1207 Release v2.21.1
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  CHANGELOG.md
  apps/main-cf.yml.j2
  requirements-all.txt
Labels: patch

#1217 update tag to latest
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1218 Release v2.21.1
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1215 Parallelize subscription handling using manager/worker model
  CHANGELOG.md
  Makefile
  apps/main-cf.yml.j2
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-manager/subscription-manager-cf.yml.j2
  apps/subscription-worker/src/subscription_worker.py
  apps/subscription-worker/subscription-worker-cf.yml.j2
  requirements-all.txt
  requirements-apps-subscription-manager.txt
  requirements-apps-subscription-worker.txt
  tests/test_subscription_manager.py
  tests/test_subscription_worker.py
Labels: patch

#1227 Convert decimals to numbers in subscription worker payload
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
Labels: bug, bumpless
