Repository ASFHyP3/hyp3, pull requests merged in 2022-12, with the labels that each got.

#1351 Release v2.21.9
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1352 Release v2.21.10
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
Labels: patch

#1354 Increase vcpu and budget for edc prod
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
Labels: patch

#1357 Release 2.21.11
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1331 Add `lambda_logging` package and log unhandled exceptions
  .gitignore
  CHANGELOG.md
  Makefile
  apps/start-execution-manager/src/start_execution_manager.py
  apps/start-execution-worker/src/start_execution_worker.py
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
  lib/lambda_logging/lambda_logging/__init__.py
  lib/lambda_logging/setup.py
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  requirements-apps-subscription-manager.txt
  requirements-apps-subscription-worker.txt
  tests/test_subscription_worker.py
Labels: bug, patch

#1364 Release 2.21.12
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  .gitignore
  CHANGELOG.md
  Makefile
  apps/start-execution-manager/src/start_execution_manager.py
  apps/start-execution-worker/src/start_execution_worker.py
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-worker/src/subscription_worker.py
  lib/lambda_logging/lambda_logging/__init__.py
  lib/lambda_logging/setup.py
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  requirements-apps-subscription-manager.txt
  requirements-apps-subscription-worker.txt
  tests/test_subscription_worker.py
Labels: patch

#1368 Raise `UnhandledException` when Lambda function fails
  lib/lambda_logging/lambda_logging/__init__.py
  tests/test_lambda_logging.py
Labels: bumpless

#1369 Fix for logging of unhandled exceptions in Lambda functions
  lib/lambda_logging/lambda_logging/__init__.py
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_lambda_logging.py
Labels: bumpless

#1379 Update deploy-enterprise.yml to decrease lifecycle for some of JPL accounts
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1384 Release 2.22.0 - add decibel option
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/subscription-worker/src/subscription_worker.py
  job_spec/RTC_GAMMA.yml
  job_spec/RTC_GAMMA_10M.yml
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  requirements-apps-subscription-worker.txt
  tests/test_subscription_worker.py
Labels: minor
