Repository ASFHyP3/hyp3, pull requests merged in 2022-02, with the labels that each got.

#816 Release version 2.8.3
  .github/workflows/deploy.yml
  CHANGELOG.md
Labels: patch

#818 Add documentation about deploying to JPL
  CHANGELOG.md
  README.md
  docs/deployments/JPL-deployment-policy.yml
  docs/deployments/JPL-deployment.md
Labels: documentation

#817 Temporarily commenting out deployments with active processing campaigns
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#826 Release 2.8.4
  .github/workflows/deploy.yml
  CHANGELOG.md
  README.md
  apps/main-cf.yml.j2
  apps/workflow-cf.yml.j2
  docs/deployments/JPL-deployment-policy.yml
  docs/deployments/JPL-deployment.md
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
  job_spec/RTC_GAMMA.yml
  job_spec/WATER_MAP.yml
  requirements-all.txt
Labels: patch

#839 convert float values to Decimals in dynamo.jobs.update_job
  lib/dynamo/dynamo/jobs.py
  tests/test_dynamo/test_jobs.py
Labels: bumpless

#837 Update JPL-deployment.md
  docs/deployments/JPL-deployment.md
Labels: bumpless, dependencies

#840 delete the environment hype-autorift in the deploy.yml
  .github/workflows/deploy.yml
Labels: bumpless

#844 Reorganize deployments
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
Labels: CI/CD, bumpless

#846 Add tests for Landsat-9 scenes
  tests/test_api/test_submit_job.py
  tests/test_api/test_validation.py
Labels: bumpless

#850 Release Landsat 9 processing for autoRIFT
  CHANGELOG.md
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  tests/test_api/test_submit_job.py
  tests/test_api/test_validation.py
Labels: minor

#857 Release v2.11.0
  .github/actions/deploy-hyp3/action.yml
  CHANGELOG.md
  README.md
  apps/api/api-cf.yml.j2
  apps/main-cf.yml.j2
  docs/deployments/JPL-deployment-policy-cf.yml
  docs/deployments/JPL-deployment.md
  requirements-all.txt
  requirements-apps-api.txt
Labels: minor

#858 Add hyp3-a19-jpl JPL deployment
  .github/workflows/deploy-enterprise.yml
Labels: CI/CD, bumpless
