Repository ASFHyP3/hyp3, pull requests merged in 2022-07, with the labels that each got.

#1105 Update to JPL-public security environments
  .github/workflows/deploy-enterprise.yml
Labels: CI/CD, bumpless

#1104 Release v2.19.5
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/scale-cluster/scale-cluster-cf.yml.j2
  apps/scale-cluster/src/scale_cluster.py
  requirements-apps-api.txt
  tests/test_scale_cluster.py
Labels: patch

#1118 Release v2.19.6
  CHANGELOG.md
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_10M.yml
  requirements-all.txt
  requirements-apps-process-new-granules.txt
Labels: patch

#1128 Increase watermap timeout to 10 hours
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_10M.yml
Labels: bumpless

#1129 Bump boto3 from 1.24.38 to 1.24.40
  requirements-all.txt
Labels: bumpless

#1131 Release v2.19.7
  CHANGELOG.md
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_10M.yml
  requirements-all.txt
Labels: patch
