Repository ASFHyP3/hyp3, pull requests merged in 2022-01, with the labels that each got.

#725 Use reusable workflows
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/deploy.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .gitleaks.toml
  .trufflehog.txt
Labels: CI/CD, bumpless

#765 Bump product lifecycle window for ISCE deployments
  .github/workflows/deploy.yml
Labels: CI/CD, bumpless

#767 Release v2.7.5
  .github/queries/asssociated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/deploy.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .gitleaks.toml
  .trufflehog.txt
  CHANGELOG.md
  apps/monitoring-cf.yml
  requirements-all.txt
  requirements-apps-api.txt
Labels: patch

#787 Fix typo in Makefile
  Makefile
Labels: bumpless

#788 Release 2.7.6
  .github/actions/deploy-hyp3/action.yml
  CHANGELOG.md
  Makefile
  README.md
  requirements-all.txt
  requirements-apps-api.txt
Labels: patch

#779 add deployment for earthdata cloud production account
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
Labels: bumpless

#792 Release v2.7.7
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  CHANGELOG.md
  apps/api/api-cf.yml
  apps/compute-cf.yml
  apps/get-files/get-files-cf.yml
  apps/process-new-granules/process-new-granules-cf.yml
  apps/scale-cluster/scale-cluster-cf.yml
  apps/start-execution/start-execution-cf.yml
  apps/update-db/update-db-cf.yml
  apps/upload-log/upload-log-cf.yml
  apps/workflow-cf.yml.j2
  requirements-all.txt
  tests/test_api/test_submit_job.py
Labels: patch

#796 Release v2.8.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy.yml
  .github/workflows/static-analysis.yml
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  apps/api/api-cf.yml.j2
  apps/compute-cf.yml.j2
  apps/get-files/get-files-cf.yml.j2
  apps/main-cf.yml.j2
  apps/monitoring-cf.yml.j2
  apps/process-new-granules/process-new-granules-cf.yml.j2
  apps/render_cf.py
  apps/scale-cluster/scale-cluster-cf.yml.j2
  apps/start-execution/start-execution-cf.yml.j2
  apps/update-db/update-db-cf.yml.j2
  apps/upload-log/upload-log-cf.yml.j2
  apps/workflow-cf.yml.j2
  requirements-all.txt
Labels: minor

#797 add .$ to step function field name so input values are correctly tran…
  apps/step-function.json.j2
Labels: bumpless

#799 update logical name of batch queue to force replacement to update SchedulingPolicyArn
  apps/compute-cf.yml.j2
Labels: bumpless

#802 explicitly define default ShareIdentifier in Scheduling Policy defini…
  apps/compute-cf.yml.j2
Labels: bumpless

#806 Releave v2.8.1
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/handlers.py
  apps/compute-cf.yml.j2
  apps/step-function.json.j2
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/user.py
  tests/test_dynamo/test_jobs.py
Labels: patch

#809 increase size of autoscaling fleets in earthdata cloud environments
  .github/workflows/deploy.yml
Labels: bumpless

#810 remove items from developer checklist that are now handled automatically
  .github/PULL_REQUEST_TEMPLATE/release.md
Labels: bumpless

#812 run cfn-lint for all environments even when one fails
  .github/workflows/static-analysis.yml
Labels: bumpless

#811 Allow subscriptions with many unprocessed granules to run before timing out
  .github/PULL_REQUEST_TEMPLATE/release.md
  .github/workflows/deploy.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  apps/process-new-granules/src/process_new_granules.py
  requirements-all.txt
  tests/test_process_new_granules.py
Labels: patch
