Repository ASFHyP3/hyp3, pull requests merged in 2022-03, with the labels that each got.

#872 Expand the fleet size for hyp3-its-live
  .github/workflows/deploy-enterprise.yml
Labels: CI/CD, bumpless

#873 Revert "Add hyp3-a19-jpl JPL deployment"
  .github/workflows/deploy-enterprise.yml
Labels: bug, CI/CD, bumpless

#877 Release v2.12.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  Makefile
  apps/compute-cf.yml.j2
  apps/main-cf.yml.j2
  apps/render_cf.py
  apps/workflow-cf.yml.j2
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
  job_spec/RTC_GAMMA.yml
  job_spec/WATER_MAP.yml
  requirements-all.txt
  requirements-apps-api.txt
Labels: minor

#883 Release v2.12.1
  .github/workflows/deploy-enterprise.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  apps/api/api-cf.yml.j2
  apps/check-processing-time/check-processing-time-cf.yml.j2
  apps/compute-cf.yml.j2
  apps/get-files/get-files-cf.yml.j2
  apps/main-cf.yml.j2
  apps/process-new-granules/process-new-granules-cf.yml.j2
  apps/render_cf.py
  apps/scale-cluster/scale-cluster-cf.yml.j2
  apps/start-execution/start-execution-cf.yml.j2
  apps/update-db/update-db-cf.yml.j2
  apps/upload-log/upload-log-cf.yml.j2
  apps/workflow-cf.yml.j2
  docs/deployments/JPL-deployment.md
  requirements-all.txt
Labels: patch

#890 add description to secrets manager secret
  apps/main-cf.yml.j2
Labels: bumpless

#889 use explicit launch template version in compute environment definition
  apps/compute-cf.yml.j2
Labels: bumpless

#888 Release v2.13.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.md
  apps/api/api-cf.yml.j2
  apps/check-processing-time/check-processing-time-cf.yml.j2
  apps/compute-cf.yml.j2
  apps/get-files/get-files-cf.yml.j2
  apps/main-cf.yml.j2
  apps/process-new-granules/process-new-granules-cf.yml.j2
  apps/scale-cluster/scale-cluster-cf.yml.j2
  apps/start-execution/start-execution-cf.yml.j2
  apps/update-db/update-db-cf.yml.j2
  apps/upload-log/upload-log-cf.yml.j2
  apps/workflow-cf.yml.j2
  lib/dynamo/setup.py
  requirements-all.txt
  tests/test_api/conftest.py
  tests/test_api/test_validation.py
Labels: minor

#891 Add missing instance type to hyp3-a19-jpl
  .github/workflows/deploy-enterprise.yml
Labels: bug, bumpless

#894 Release v2.14.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/get-files/get-files-cf.yml.j2
  apps/get-files/src/get_files.py
  apps/main-cf.yml.j2
  apps/workflow-cf.yml.j2
  requirements-all.txt
  tests/test_get_files.py
Labels: minor

#899 ASF Deployment documentation
  docs/deployments/ASF-deployment-ci-cf.yml
  docs/deployments/ASF-deployment.md
Labels: documentation, bumpless

#902 expand the fleet size for ITS_LIVE processing
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#905 Add hyp3-avo deployment to enterprise deploy workflow
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#917 Up vCPUs for hyp3-isce
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#913 Release v2.14.1
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/main-cf.yml.j2
  apps/step-function.json.j2
  docs/deployments/ASF-deployment-ci-cf.yml
  docs/deployments/ASF-deployment.md
  requirements-all.txt
  requirements-apps-api.txt
Labels: patch

#916 Add an environmnet.yml
  environment.yml
Labels: bumpless

#918 retire obsolete hyp3-autorift-eu environment
  .github/workflows/deploy-enterprise.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
Labels: bumpless

#920 Bring watermap deployment into our normal deployment workflow
  .github/workflows/deploy-enterprise.yml
  job_spec/RTC_GAMMA_10M.yml
  job_spec/WATER_MAP_10M.yml
Labels: bumpless

#922 Release v2.14.2
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/step-function.json.j2
  environment.yml
  job_spec/AUTORIFT_ITS_LIVE_EU.yml
  job_spec/RTC_GAMMA_10M.yml
  job_spec/WATER_MAP_10M.yml
Labels: patch

#925 Set AVO product lifetime to 1000 years
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#926 AVO expiration time, boto3 update
  .github/workflows/deploy-enterprise.yml
  requirements-all.txt
Labels: bumpless

#933 Upgrade flask from 2.0.1 to 2.1.0
  requirements-apps-api.txt
Labels: bumpless

#932 Subscription decimals
  CHANGELOG.md
  lib/dynamo/dynamo/subscriptions.py
  tests/test_dynamo/test_subscriptions.py
Labels: patch

#935 Watermap subscriptions
  CHANGELOG.md
  apps/process-new-granules/src/process_new_granules.py
Labels: patch

#937 Fix Changelog, pin botocore version to fix tests
  CHANGELOG.md
  requirements-all.txt
Labels: bumpless

#938 Release 2.14.3
  CHANGELOG.md
  apps/process-new-granules/src/process_new_granules.py
  lib/dynamo/dynamo/subscriptions.py
  requirements-all.txt
  requirements-apps-api.txt
  tests/test_dynamo/test_subscriptions.py
Labels: patch

#943 Hotfix: S2 fleet size for ITS_LIVE
  .github/workflows/deploy-enterprise.yml
Labels: bumpless
