Repository ASFHyP3/hyp3, pull requests merged in 2022-05, with the labels that each got.

#991 revist hyp3-tibet vcpus to 3,200
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#988 Release v2.15.0
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_10M.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-process-new-granules.txt
  tests/test_api/test_submit_job.py
Labels: minor

#986 Don't change status from PENDING to RUNNING until Batch job starts running
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/handle-batch-event/handle-batch-event-cf.yml.j2
  apps/handle-batch-event/src/handle_batch_event.py
  apps/main-cf.yml.j2
  apps/start-execution/src/start_execution.py
  apps/step-function.json.j2
  lib/dynamo/dynamo/jobs.py
  requirements-all.txt
  requirements-apps-handle-batch-event.txt
  tests/test_dynamo/test_jobs.py
  tests/test_handle_batch_event.py
Labels: minor

#998 Handle missing log stream
  CHANGELOG.md
  apps/upload-log/src/upload_log.py
  tests/test_upload_log.py
Labels: bug, patch

#1000 Fix log stream key error
  apps/upload-log/src/upload_log.py
  tests/test_upload_log.py
Labels: bug, bumpless

#1003 Release 2.16.1
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/check-processing-time/src/check_processing_time.py
  apps/step-function.json.j2
  apps/upload-log/src/upload_log.py
  requirements-all.txt
  tests/test_check_processing_time.py
  tests/test_upload_log.py
Labels: patch

#1007 Bumpless release for library upgrades
  requirements-all.txt
  requirements-apps-api.txt
Labels: bumpless

#1006 remove unused functions from api.util
  apps/api/src/hyp3_api/util.py
Labels: bumpless

#1010 Allow unlimited quota, priority override
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/user.py
  tests/test_api/test_get_user.py
  tests/test_api/test_list_jobs.py
  tests/test_dynamo/test_jobs.py
  tests/test_dynamo/test_user.py
  tests/test_start_execution.py
Labels: minor

#1013 Release 2.17.0
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/api/src/hyp3_api/util.py
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/user.py
  requirements-all.txt
  requirements-apps-api.txt
  tests/test_api/test_get_user.py
  tests/test_api/test_list_jobs.py
  tests/test_dynamo/test_jobs.py
  tests/test_dynamo/test_user.py
  tests/test_start_execution.py
Labels: minor

#1016 Fix get jobs waiting for execution
  CHANGELOG.md
  lib/dynamo/dynamo/jobs.py
Labels: bug, patch

#1018 change security environment for hyp3-a19-jpl from JPL to JPL-public
  .github/workflows/deploy-enterprise.yml
  apps/main-cf.yml.j2
Labels: bumpless

#1017 Relase 2.17.1
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml
  apps/main-cf.yml.j2
  apps/step-function.json.j2
  lib/dynamo/dynamo/jobs.py
  requirements-all.txt
  requirements-apps-process-new-granules.txt
  tests/test_process_new_granules.py
Labels: patch

#1029 extend-s2-filename
  CHANGELOG.md
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  requirements-all.txt
  tests/test_api/test_submit_job.py
Labels: patch

#1025 Update README.md
  README.md
Labels: documentation, bumpless

#1035 Release 2.17.4
  .github/workflows/static-analysis.yml
  .snyk
  CHANGELOG.md
  README.md
  requirements-all.txt
  requirements-apps-process-new-granules.txt
Labels: patch
