Repository ASFHyP3/hyp3, pull requests merged in 2023-06, with the labels that each got.

#1653 increase INSAR_ISCE_BURST timeout to 90 minutes
  job_spec/INSAR_ISCE_BURST.yml
Labels: bumpless

#1654 Revert "Bump requests from 2.29.0 to 2.31.0"
  requirements-apps-api.txt
Labels: bumpless

#1658 Release v3.8.0
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/validation.py
  job_spec/AUTORIFT.yml
  job_spec/INSAR_ISCE_BURST.yml
  job_spec/S1_CORRECTION_ITS_LIVE.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_api/test_validation.py
Labels: minor

#1662 Add hyp3-pdc deployment
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
Labels: minor

#1663 Release v3.9.0
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
Labels: minor

#1671 Release v3.9.1
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  lib/dynamo/setup.py
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  requirements-apps-subscription-worker.txt
Labels: patch

#1674 Release v3.9.2
  CHANGELOG.md
  requirements-apps-subscription-worker.txt
Labels: patch

#1681 Add jobs query pagination in subscriptions worker
  CHANGELOG.md
  apps/subscription-worker/src/subscription_worker.py
  tests/test_subscription_worker.py
Labels: patch

#1685 Release 3.9.3
  CHANGELOG.md
  apps/start-execution-manager/src/start_execution_manager.py
  apps/subscription-worker/src/subscription_worker.py
  tests/test_start_execution_manager.py
  tests/test_subscription_worker.py
Labels: patch

#1690 Start up to 2 batches of 300 jobs at once
  CHANGELOG.md
  apps/start-execution-manager/src/start_execution_manager.py
  tests/test_start_execution_manager.py
Labels: patch

#1691 Release v3.9.4
  CHANGELOG.md
  apps/start-execution-manager/src/start_execution_manager.py
  tests/test_start_execution_manager.py
Labels: patch

#1694 Add `create-jira-issue.yml`
  .github/workflows/create-jira-issue.yml
Labels: bumpless
