Repository ASFHyP3/hyp3, pull requests merged in 2023-12, with the labels that each got.

#1967 Release v4.5.0
  CHANGELOG.md
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#1980 Fix numeric type in INSAR_ISCE_TEST
  CHANGELOG.md
  job_spec/INSAR_ISCE_TEST.yml
Labels: bug

#1981 Release v4.5.1 -- output_resolution numeric type fix
  CHANGELOG.md
  job_spec/INSAR_ISCE_TEST.yml
Labels: patch

#1992 Release v5.0.0
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/dem_coverage_map_legacy.geojson
  apps/api/src/hyp3_api/validation.py
  job_spec/INSAR_ISCE_BURST.yml
  job_spec/RTC_GAMMA.yml
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_api/test_validation.py
Labels: major
