Repository ASFHyP3/hyp3, pull requests merged in 2023-05, with the labels that each got.

#1593 Release v3.4.0
  .github/workflows/changelog.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  apps/step-function.json.j2
  job_spec/WATER_MAP.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#1598 upgrade flask to v2.2.5
  requirements-apps-api.txt
Labels: bumpless

#1604 fix changelog
  CHANGELOG.md
Labels: bumpless

#1605 Fix `WATER_MAP_EQ` command
  job_spec/WATER_MAP_EQ.yml
Labels: bug, bumpless

#1607 Increase memory for high-res WATER_MAP_EQ jobs
  apps/step-function.json.j2
Labels: bumpless

#1606 Release v3.5.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  apps/step-function.json.j2
  job_spec/RTC_GAMMA.yml
  job_spec/WATER_MAP_EQ.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#1613 Change job status to RUNNING only if currently PENDING
  CHANGELOG.md
  apps/handle-batch-event/src/handle_batch_event.py
  tests/test_handle_batch_event.py
Labels: patch

#1620 Release v3.5.1
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/handle-batch-event/handle-batch-event-cf.yml.j2
  apps/handle-batch-event/src/handle_batch_event.py
  job_spec/INSAR_GAMMA_HIGH_MEMORY.yml
  requirements-all.txt
  tests/test_handle_batch_event.py
Labels: patch

#1618 Query other users' jobs
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/routes.py
  tests/test_api/test_list_jobs.py
Labels: minor

#1624 Release v3.6.0
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/routes.py
  job_spec/WATER_MAP_EQ.yml
  tests/test_api/test_list_jobs.py
Labels: minor

#1633 Fix job type name in water map test job spec
  job_spec/WATER_MAP_TEST.yml
Labels: bug, bumpless

#1634 Allow for nullable known_water_threshold
  job_spec/WATER_MAP_TEST.yml
Labels: bug, bumpless

#1635 fix minimization metric argument
  job_spec/WATER_MAP_TEST.yml
Labels: bug, bumpless

#1640 Make flood-depth-estimator nullable
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_TEST.yml
Labels: bug, bumpless
