Repository ASFHyP3/hyp3, pull requests merged in 2023-08, with the labels that each got.

#1752 Remove c5 instances with less disk for INSAR ISCE jobs
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#1755 Release v3.9.8
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_api/test_util.py
Labels: patch

#1758 Add `INSAR_ISCE_BURST` job type to `hyp3-test` deployment
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
Labels: minor

#1759 Release 3.4.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  job_spec/INSAR_ISCE_TEST.yml
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#1761 Fix version in Changelog
  CHANGELOG.md
Labels: bumpless

#1762 Fix changelog version
  CHANGELOG.md
Labels: bumpless

#1764 Release v3.10.1
  CHANGELOG.md
  apps/main-cf.yml.j2
Labels: patch

#1772 Add Subscriptions deprecation warning to Changelog
  CHANGELOG.md
Labels: patch

#1773 Release v3.10.2
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1781 Release 3.10.3
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  requirements-apps-subscription-worker.txt
Labels: patch

#1786 fix ami id mismatch in deploy-daac.yml
  .github/workflows/deploy-daac.yml
Labels: bumpless

#1790 Release v3.10.4
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1791 Release v3.10.5
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  job_spec/INSAR_ISCE.yml
Labels: patch

#1793 Release v3.10.6
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
Labels: patch

#1795 Release 3.10.7
  CHANGELOG.md
  apps/api/src/hyp3_api/validation.py
  job_spec/INSAR_ISCE_BURST.yml
  tests/test_api/test_validation.py
Labels: enhancement, patch

#1800 Release v3.10.8 -- JPL On Demand
  CHANGELOG.md
  apps/compute-cf.yml.j2
Labels: patch

#1804 Release v3.10.9
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/main-cf.yml.j2
Labels: patch
