Repository ASFHyP3/hyp3, pull requests merged in 2023-01, with the labels that each got.

#1395 Pin setuptools to address snyk vulernability
  requirements-all.txt
Labels: bug, bumpless

#1400 set --omp-num-threads=4 for daac autorift jobs
  CHANGELOG.md
  job_spec/AUTORIFT.yml
Labels: bumpless

#1405 Release v2.23.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  job_spec/AUTORIFT.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/RTC_GAMMA.yml
  job_spec/WATER_MAP.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#1406 string comparison for resolution in step function
  apps/step-function.json.j2
Labels: bumpless

#1407 lower memory requirements for 10m RTC jobs
  apps/step-function.json.j2
Labels: bumpless

#1410 increase RTC_GAMMA timeout from 3 hours to 10 hours
  job_spec/RTC_GAMMA.yml
Labels: bumpless

#1431 Fix calcDelaysGUNW caps
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
Labels: bug, bumpless

#1435 Release v2.25.0
  CHANGELOG.md
  apps/step-function.json.j2
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#1426 Split `WATER_MAP` and `RIVER_WIDTH` jobs into multiple tasks
  CHANGELOG.md
  job_spec/RIVER_WIDTH.yml
  job_spec/WATER_MAP.yml
Labels: major

#1439 Add details on step function updates to release checklist
  .github/workflows/release-template-comment.yml
Labels: bumpless

#1455 Increase flood map, water map, and river width timeouts
  job_spec/RIVER_WIDTH.yml
  job_spec/WATER_MAP.yml
Labels: bug, bumpless

#1457 reduce product lifetime for hyp3-its-life to 45 days
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
Labels: patch

#1458 Add hyp3-bgc-engineering to enterprise deployements
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
Labels: patch

#1463 Increase RIVER_WIDTH_RTC memory
  job_spec/RIVER_WIDTH.yml
Labels: bug, bumpless
