Repository ASFHyP3/hyp3, pull requests merged in 2023-10, with the labels that each got.

#1866 Release 4.1.1
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/dem_coverage_map_cop30.geojson
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: enhancement, patch

#1869 Use exponential backoff retry strategy
  CHANGELOG.md
  apps/step-function.json.j2
Labels: patch

#1871 Release v4.1.2
  CHANGELOG.md
  apps/step-function.json.j2
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1877 Don't require float format for phase filter param
  job_spec/INSAR_GAMMA.yml
Labels: bumpless

#1882 Improve `phase_filter_parameter` description
  job_spec/INSAR_GAMMA.yml
Labels: bumpless

#1889 Remove the `INSAR_GAMMA_TEST` job type
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  job_spec/INSAR_GAMMA_TEST.yml
Labels: bumpless

#1890 Improve `phase_filter_parameter` description
  job_spec/INSAR_GAMMA.yml
Labels: bumpless

#1886 Release v4.2.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_GAMMA_TEST.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_api/conftest.py
  tests/test_api/test_api_spec.py
Labels: minor

#1893 Release v4.2.1
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1901 update ec2 user data for al2023
  apps/compute-cf.yml.j2
Labels: bumpless

#1900 lower job memory reservations to accomodate AL2023 AMI
  apps/step-function.json.j2
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/RIVER_WIDTH.yml
  job_spec/RTC_GAMMA.yml
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_EQ.yml
  job_spec/WATER_MAP_TEST.yml
Labels: bumpless
