Repository ASFHyP3/hyp3, pull requests merged in 2023-09, with the labels that each got.

#1812 Release 3.10.10
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#1818 Release v4.0.0
  CHANGELOG.md
  Makefile
  apps/api/api-cf.yml.j2
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/routes.py
  apps/main-cf.yml.j2
  apps/subscription-manager/src/subscription_manager.py
  apps/subscription-manager/subscription-manager-cf.yml.j2
  apps/subscription-worker/src/subscription_worker.py
  apps/subscription-worker/subscription-worker-cf.yml.j2
  lib/dynamo/dynamo/__init__.py
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/subscriptions.py
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  requirements-apps-subscription-manager.txt
  requirements-apps-subscription-worker.txt
  tests/cfg.env
  tests/conftest.py
  tests/test_api/conftest.py
  tests/test_api/test_api_spec.py
  tests/test_api/test_list_jobs.py
  tests/test_api/test_subscriptions.py
  tests/test_dynamo/test_jobs.py
  tests/test_dynamo/test_subscriptions.py
  tests/test_subscription_manager.py
  tests/test_subscription_worker.py
Labels: major

#1836 Optional param file for `AUTORIFT_ITS_LIVE` and `AUTORIFT_ITS_LIVE_TEST`
  CHANGELOG.md
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
Labels: minor

#1838 Replace `AUTORIFT` with `AUTORIFT_ITS_LIVE` in `hyp3-enterprise-test`
  .github/workflows/deploy-enterprise-test.yml
Labels: bumpless

#1839 Provide api_spec for autoRIFT parameter file argument
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
Labels: bug

#1840 Provide api_spec for autoRIFT parameter file argument
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
Labels: bug, bumpless

#1837 Release v4.1.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
  requirements-all.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#1846 fix spelling error
  job_spec/WATER_MAP_TEST.yml
Labels: bumpless

#1849 Delete `INSAR_GAMMA_HIGH_MEMORY.yml`
  .github/workflows/deploy-enterprise.yml
  job_spec/INSAR_GAMMA_HIGH_MEMORY.yml
Labels: bumpless

#1853 Bumpless release
  .github/workflows/deploy-enterprise.yml
  job_spec/INSAR_GAMMA_HIGH_MEMORY.yml
  job_spec/WATER_MAP_TEST.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: bumpless
