Repository ASFHyP3/hyp3, pull requests merged in 2024-04, with the labels that each got.

#2175 Release v7.0.0
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
Labels: major

#2216 make weather model a required parameter for ARIA_RAIDER jobs
  job_spec/ARIA_RAIDER.yml
Labels: bug, bumpless

#2217 Release v7.1.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/job_parameters.yml.j2
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/util.py
  docs/deployments/JPL-deployment-policy-cf.yml
  job_spec/ARIA_RAIDER.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_TEST.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_api/test_util.py
  tests/test_api/test_validation.py
  tests/test_dynamo/test_jobs.py
Labels: minor
