Repository ASFHyP3/hyp3, pull requests merged in 2024-09, with the labels that each got.

#2407 Release v7.8.1
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#2420 Release v7.9.0
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  job_spec/ARIA_AUTORIFT.yml
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/INSAR_ISCE.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#2430 Add String Default for `bounds` for CloudFormation
  job_spec/SRG_GSLC.yml
Labels: bumpless

#2431 Release v7.9.1
  CHANGELOG.md
  job_spec/SRG_GSLC.yml
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#2435 Release v7.9.2
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  docs/deployments/ASF-deployment-ci-cf.yml
Labels: patch

#2437 Release v7.9.3
  CHANGELOG.md
  docs/deployments/ASF-deployment-ci-cf.yml
Labels: patch
