Repository ASFHyP3/hyp3, pull requests merged in 2024-02, with the labels that each got.

#2061 quota yes/no strings to keep yaml parser from changing them to true/false
  apps/main-cf.yml.j2
Labels: bumpless

#2073 remove unused component definitions from api spec
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
Labels: bumpless

#2079 include `dynamo/*.json` files
  lib/dynamo/setup.py
Labels: bumpless

#2080 Release v6.1.0
  .github/workflows/deploy-enterprise.yml
  .gitignore
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/render_cf.py
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/setup.py
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_dynamo/test_jobs.py
Labels: minor

#2086 upgrade to openapi-core 0.19.0
  requirements-apps-api.txt
Labels: bumpless

#2102 remove newline in release checklist to avoid double-spacing the entire list
  .github/workflows/release-template-comment.yml
Labels: bumpless

#2101 Release v6.1.1
  .github/workflows/release-template-comment.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#2106 pass `cost_profile` to deploy action
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#2111 Release v6.2.0
  .github/actions/deploy-hyp3/action.yml
  .github/workflows/deploy-credits-sandbox.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .gitignore
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/routes.py
  apps/render_cf.py
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_BURST.yml
  job_spec/INSAR_ISCE_TEST.yml
  job_spec/RTC_GAMMA.yml
  job_spec/S1_CORRECTION_ITS_LIVE.yml
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_EQ.yml
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/user.py
  lib/dynamo/setup.py
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_api/conftest.py
  tests/test_api/test_get_costs.py
  tests/test_dynamo/test_jobs.py
Labels: minor

#2116 remove vestiges of legacy dem implementation
  apps/api/src/hyp3_api/validation.py
  tests/test_api/test_validation.py
Labels: bumpless
