Repository ASFHyP3/hyp3, pull requests merged in 2024-08, with the labels that each got.

#2372 Release v7.7.1
  CHANGELOG.md
  job_spec/ARIA_AUTORIFT.yml
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE_BURST.yml
  job_spec/RTC_GAMMA.yml
  job_spec/S1_CORRECTION_ITS_LIVE.yml
  job_spec/SRG_GSLC_CPU.yml
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_EQ.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch

#2373 Changed SRG_GSLC_CPU Job to Use the hyp3-srg Image
  CHANGELOG.md
  job_spec/SRG_GSLC_CPU.yml
Labels: patch

#2374 Rename SRG_GSLC_CPU to SRG_GSLC
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  job_spec/SRG_GSLC.yml
Labels: patch

#2375 Release v7.7.2
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  job_spec/SRG_GSLC.yml
Labels: patch

#2385 fix INSAR_MULTI_BURST example scene names
  job_spec/INSAR_MULTI_BURST.yml
Labels: bumpless

#2388 Add burst job reformatting to Changelog
  CHANGELOG.md
Labels: bumpless

#2398 Add Correct AMI and Image Tag for SRG
  job_spec/SRG_GSLC.yml
Labels: bumpless

#2397 Release v7.8.0
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  apps/compute-cf.yml.j2
  apps/handle-batch-event/handle-batch-event-cf.yml.j2
  apps/main-cf.yml.j2
  apps/scale-cluster/scale-cluster-cf.yml.j2
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
  job_spec/ARIA_AUTORIFT.yml
  job_spec/ARIA_RAIDER.yml
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE.yml
  job_spec/INSAR_ISCE_BURST.yml
  job_spec/RTC_GAMMA.yml
  job_spec/S1_CORRECTION_ITS_LIVE.yml
  job_spec/SRG_GSLC.yml
  job_spec/WATER_MAP.yml
  job_spec/WATER_MAP_EQ.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor
