Repository ASFHyP3/hyp3, pull requests merged in 2024-03, with the labels that each got.

#2140 Release v6.3.0
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/validation.py
  apps/render_cf.py
  job_spec/INSAR_GAMMA.yml
  job_spec/RTC_GAMMA.yml
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/setup.py
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/test_api/test_validation.py
  tests/test_dynamo/test_jobs.py
Labels: minor

#2146 Release v6.4.0
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
  Makefile
  apps/disable-private-dns/disable-private-dns-cf.yml.j2
  apps/disable-private-dns/src/disable_private_dns.py
  apps/main-cf.yml.j2
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#2163 Delete `credits-sandbox` deployment
  .github/workflows/deploy-credits-sandbox.yml
Labels: bumpless

#2165 rename autorift secrets for container changes
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
Labels: bumpless

#2160 Release v6.5.0
  .github/workflows/deploy-credits-sandbox.yml
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/AUTORIFT_ITS_LIVE_TEST.yml
  requirements-all.txt
  requirements-apps-scale-cluster.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: minor

#2173 Release v6.5.1
  CHANGELOG.md
  Makefile
  apps/disable-private-dns/disable-private-dns-cf.yml.j2
  apps/disable-private-dns/src/disable_private_dns.py
  apps/main-cf.yml.j2
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
Labels: patch
