Repository ASFHyP3/hyp3, pull requests merged in 2024-05, with the labels that each got.

#2223 Update dependabot.yml to weekly
  .github/dependabot.yml
Labels: bumpless

#2243 Release v7.1.1
  .github/dependabot.yml
  CHANGELOG.md
  apps/start-execution-manager/src/start_execution_manager.py
  tests/test_start_execution_manager.py
Labels: patch

#2262 remove unneeded Werkzeug pin in api requirements; see #1861
  requirements-apps-api.txt
Labels: bumpless

#2271 Release 7.2.1
  CHANGELOG.md
  lib/dynamo/setup.py
Labels: patch

#2295 fix changelog
  CHANGELOG.md
Labels: bumpless

#2294 Release v7.3.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/deploy-whitelisting-sandbox.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  apps/api/api-cf.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/handlers.py
  apps/main-cf.yml.j2
  lib/dynamo/dynamo/exceptions.py
  lib/dynamo/dynamo/jobs.py
  lib/dynamo/dynamo/user.py
  lib/dynamo/dynamo/util.py
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution-manager.txt
  requirements-apps-start-execution-worker.txt
  tests/cfg.env
  tests/conftest.py
  tests/test_api/test_get_user.py
  tests/test_api/test_patch_user.py
  tests/test_api/test_submit_job.py
  tests/test_dynamo/test_jobs.py
  tests/test_dynamo/test_user.py
Labels: minor

#2297 Release v7.4.0
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
Labels: minor
