Repository ASFHyP3/hyp3, pull requests merged in 2025-05, with the labels that each got.

#2750 Additional edits to error messages
  apps/api/src/hyp3_api/validation.py
  tests/test_api/test_opera_rtc_s1.py
  tests/test_api/test_validation.py
Labels: bumpless

#2748 add hyphen in OPERA RTC-S1
  apps/api/src/hyp3_api/validation.py
  tests/test_api/test_opera_rtc_s1.py
  tests/test_api/test_validation.py
Labels: bumpless

#2753 allow later opera rtc products
  apps/api/src/hyp3_api/validation.py
Labels: bumpless

#2749 Release v10.5.0
  .github/workflows/deploy-daac-test.yml
  .github/workflows/deploy-multi-burst-sandbox.yml
  CHANGELOG.md
  Makefile
  README.md
  apps/api/api-cf.yml.j2
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/validation.py
  apps/main-cf.yml.j2
  job_spec/OPERA_RTC_S1.yml
  pyproject.toml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-start-execution.txt
  tests/cfg.env
  tests/test_api/conftest.py
  tests/test_api/test_opera_rtc_s1.py
  tests/test_api/test_submit_job.py
  tests/test_api/test_validation.py
Labels: minor

#2773 Update deployment docs for EDC
  README.md
Labels: bumpless

#2784 Release v10.5.2
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/deploy-multi-burst-sandbox.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag-version.yml
  CHANGELOG.md
  README.md
  job_spec/OPERA_RTC_S1.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-start-execution.txt
Labels: patch
