Repository ASFHyP3/hyp3, pull requests merged in 2025-06, with the labels that each got.

#2797 Release v10.6.0
  CHANGELOG.md
  Makefile
  job_spec/ARIA_AUTORIFT.yml
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-start-execution.txt
  tests/conftest.py
Labels: minor

#2801 Release v10.7.0
  CHANGELOG.md
  job_spec/ARIA_S1_GUNW.yml
  job_spec/INSAR_ISCE.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-start-execution.txt
Labels: minor

#2810 Release v10.8.0
  CHANGELOG.md
  apps/api/src/hyp3_api/handlers.py
  apps/api/src/hyp3_api/validation.py
  cicd-stacks/JPL-deployment-policy-cf.yml
  job_spec/ARIA_S1_GUNW.yml
  job_spec/OPERA_RTC_S1.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-start-execution.txt
  tests/test_api/conftest.py
  tests/test_api/test_aria_s1_gunw.py
  tests/test_api/test_opera_rtc_s1.py
  tests/test_api/test_validation.py
Labels: minor

#2816 Release v10.9.1
  CHANGELOG.md
  job_spec/ARIA_S1_GUNW.yml
Labels: patch

#2820 Update README to clarify account ownership
  README.md
Labels: documentation, bumpless

#2823 Fix s3 bucket for fire safe
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
Labels: bumpless

#2824 Format changes in job spec for AK-FIRE-SAFE
  job_spec/AK_FIRE_SAFE.yml
Labels: bumpless

#2825 Fix typo in job_spec for fire-safe
  job_spec/AK_FIRE_SAFE.yml
Labels: bumpless
