Repository ASFHyP3/hyp3, pull requests merged in 2025-03, with the labels that each got.

#2639 remove obsolete ESA env vars for dockerizedtopsapp; update aria_s1_gunw example job
  job_spec/ARIA_S1_GUNW.yml
  job_spec/INSAR_ISCE.yml
Labels: bumpless

#2647 Multiburst costs
  CHANGELOG.md
  apps/render_cf.py
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE_MULTI_BURST.yml
  job_spec/RTC_GAMMA.yml
  lib/dynamo/dynamo/jobs.py
  tests/test_dynamo/test_jobs.py
Labels: major

#2649 Release v9.5.4
  .gitignore
  CHANGELOG.md
  Makefile
  apps/render_cf.py
  apps/start-execution-manager/src/start_execution_manager.py
  apps/start-execution-manager/start-execution-manager-cf.yml.j2
  apps/start-execution/src/start_execution.py
  apps/start-execution/start-execution-cf.yml.j2
  apps/workflow-cf.yml.j2
  requirements-all.txt
  requirements-apps-start-execution-worker.txt
  requirements-apps-start-execution.txt
  tests/test_start_execution.py
  tests/test_start_execution_manager.py
Labels: patch

#2662 Release v10.0.0
  .github/workflows/deploy-multi-burst-sandbox.yml
  CHANGELOG.md
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/validation.py
  apps/render_cf.py
  job_spec/INSAR_GAMMA.yml
  job_spec/INSAR_ISCE_MULTI_BURST.yml
  job_spec/RTC_GAMMA.yml
  lib/dynamo/dynamo/jobs.py
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-start-execution.txt
  tests/test_api/test_validation.py
  tests/test_dynamo/test_jobs.py
  tests/test_render_cf.py
Labels: major

#2666 Add multi burst job type to edc test deployment
  .github/workflows/deploy-daac.yml
Labels: bumpless

#2673 Release v10.1.0
  .github/workflows/deploy-daac.yml
  CHANGELOG.md
  requirements-all.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-start-execution.txt
Labels: minor

#2618 Creation of Service's Sandbox Environment
  .github/workflows/deploy-services-sandbox.yml
Labels: bumpless

#2680 update opera-disp-tms example job with frames from production archive
  job_spec/OPERA_DISP_TMS.yml
Labels: bumpless

#2678 Release v10.2.0
  .github/workflows/deploy-daac.yml
  .github/workflows/deploy-enterprise.yml
  .github/workflows/deploy-services-sandbox.yml
  CHANGELOG.md
  job_spec/OPERA_DISP_TMS.yml
Labels: minor

#2691 Release v10.3.1
  CHANGELOG.md
  apps/api/src/hyp3_api/auth.py
  apps/api/src/hyp3_api/lambda_handler.py
  apps/api/src/hyp3_api/routes.py
  apps/api/src/hyp3_api/util.py
  apps/disable-private-dns/src/disable_private_dns.py
  apps/get-files/src/get_files.py
  apps/scale-cluster/src/scale_cluster.py
  apps/start-execution/src/start_execution.py
  apps/update-db/src/main.py
  apps/upload-log/src/upload_log.py
  lib/dynamo/dynamo/user.py
  lib/dynamo/dynamo/util.py
  lib/lambda_logging/lambda_logging/__init__.py
  pyproject.toml
Labels: patch
