Repository ASFHyP3/hyp3, pull requests merged in 2025-08, with the labels that each got.

#2861 Release v10.11.0
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  Makefile
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/main-cf.yml.j2
  apps/scale-cluster/scale-cluster-cf.yml.j2
  apps/search-archive/search-archive-cf.yml.j2
  apps/search-archive/src/search_archive.py
  apps/step-function.json.j2
  apps/workflow-cf.yml.j2
  lib/dynamo/dynamo/exceptions.py
  lib/dynamo/dynamo/user.py
  lib/lambda_logging/lambda_logging/__init__.py
  requirements-all.txt
  requirements-apps-search-archive.txt
  tests/test_dynamo/test_user.py
  tests/test_search_archive.py
Labels: minor

#2874 fix deploy workflow names :facepalm:
  .github/workflows/deploy-custom-prod.yml
  .github/workflows/deploy-enterprise-prod.yml
Labels: CI/CD, bumpless

#2881 Release v10.11.2
  .github/workflows/deploy-daac-prod.yml
  .github/workflows/deploy-daac-test.yml
  CHANGELOG.md
  job_spec/OPERA_RTC_S1_SLC.yml
  requirements-all.txt
  requirements-apps-api.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-search-archive.txt
  requirements-apps-start-execution.txt
Labels: patch

#2883 Release v10.11.3
  CHANGELOG.md
  apps/compute-cf.yml.j2
  job_spec/ARIA_RAIDER.yml
  job_spec/ARIA_S1_GUNW.yml
  job_spec/INSAR_ISCE.yml
Labels: patch
