Repository ASFHyP3/hyp3, pull requests merged in 2025-07, with the labels that each got.

#2829 Release v10.10.0
  .github/workflows/deploy-enterprise-test.yml
  .github/workflows/deploy-enterprise.yml
  CHANGELOG.md
  README.md
  apps/api/api-cf.yml.j2
  apps/api/src/hyp3_api/api-spec/openapi-spec.yml.j2
  apps/api/src/hyp3_api/util.py
  apps/render_cf.py
  apps/set-batch-overrides/src/set_batch_overrides.py
  job_spec/AK_FIRE_SAFE.yml
  job_spec/ARIA_AUTORIFT.yml
  job_spec/AUTORIFT.yml
  job_spec/AUTORIFT_ITS_LIVE.yml
  job_spec/INSAR_ISCE_MULTI_BURST.yml
  job_spec/S1_CORRECTION_ITS_LIVE.yml
  requirements-all.txt
  requirements-apps-api-binary.txt
  requirements-apps-disable-private-dns.txt
  requirements-apps-get-files.txt
  requirements-apps-start-execution.txt
  tests/test_api/test_submit_job.py
  tests/test_api/test_util.py
  tests/test_set_batch_overrides.py
Labels: minor

#2837 Fix job name in ARIA_S1_COSEIS job spec
  job_spec/ARIA_S1_COSEIS.yml
Labels: bumpless

#2841 set unused opera_rtc_s1_end_date parameter to default for hyp3-opera-uat and hyp3-opera-prod deployments
  .github/workflows/deploy-daac-prod.yml
  .github/workflows/deploy-daac-test.yml
Labels: bumpless

#2839 Increase memory and timeout params for coseis-sar
  job_spec/ARIA_S1_COSEIS.yml
Labels: bumpless

#2843 set distribution-url to empty string for opera deployments
  .github/workflows/deploy-daac-prod.yml
  .github/workflows/deploy-daac-test.yml
Labels: bumpless

#2845 Release v10.10.2
  .github/workflows/deploy-daac-prod.yml
  .github/workflows/deploy-daac-test.yml
  CHANGELOG.md
  job_spec/ARIA_S1_COSEIS.yml
Labels: patch
